// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Modelo.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderItem = new HashSet<OrderItem>();
        }

        public int Id { get; set; }
        public int UserId { get; set; }
        public string Phone { get; set; }
        public string Province { get; set; }
        public string ShippingAddress { get; set; }
        public string ZipCode { get; set; }
        public decimal OrderTotal { get; set; }
        public DateTime OrderDate { get; set; }
        public string OrderStatus { get; set; }
        //de aca para abajo es nuevo
        public string NameLastName { get; set; }
        public string Email { get; set; }
        public string City { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}