// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Modelo.PrototypePatron;
using System;
using System.Collections.Generic;

namespace Modelo.Models
{
    public partial class Product: ProductPrototype
    {
        public Product()
        {
            OrderItem = new HashSet<OrderItem>();
        }

        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Storage { get; set; }
        public int Ram { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public int InStock { get; set; }
        public bool IsActive { get; set; }

        public HistoricProduct Clone()
        {
            HistoricProduct clonedProduct = new HistoricProduct
            {
                //Id = this.Id,
                OriginalId = this.Id,
                Brand = this.Brand,
                Model = this.Model,
                Storage = this.Storage,
                Ram = this.Ram,
                Description = this.Description,
                Price = this.Price,
                Image = this.Image,
                InStock = this.InStock,
                IsActive = this.IsActive,
                RegistrationDate = DateTime.Now.ToString()
            };

            return clonedProduct;
        }

        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}