// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Modelo.Models;
using System;
using System.Collections.Generic;

namespace Modelo.Models.Configurations
{
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.HasKey(e => new { e.OrderId, e.UserId, e.ProductId })
                .HasName("PK__Order__598583247F25B9C7");

            entity.Property(e => e.OrderId).HasColumnName("order_id");

            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.Property(e => e.ProductId).HasColumnName("product_id");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasColumnName("address");

            entity.Property(e => e.City).HasColumnName("city");

            entity.Property(e => e.OrderDate)
                .HasColumnType("datetime")
                .HasColumnName("order_date");

            entity.Property(e => e.Province)
                .IsRequired()
                .HasColumnName("province");

            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.Property(e => e.ZipCode)
                .IsRequired()
                .HasColumnName("zip_code");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.Order)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Order__product_i__59FA5E80");

            entity.HasOne(d => d.User)
                .WithMany(p => p.Order)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Order__user_id__59063A47");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order> entity);
    }
}
