// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Modelo.Models;
using System;
using System.Collections.Generic;

namespace Modelo.Models.Configurations
{
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("city");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("email");

            entity.Property(e => e.NameLastName)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("name_last_name");

            entity.Property(e => e.OrderDate)
                .HasColumnType("datetime")
                .HasColumnName("order_date");

            entity.Property(e => e.OrderStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("order_status");

            entity.Property(e => e.OrderTotal)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("order_total");

            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("phone");

            entity.Property(e => e.Province)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("province");

            entity.Property(e => e.ShippingAddress)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("shipping_address");

            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.Property(e => e.ZipCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("zip_code");

            entity.HasOne(d => d.User)
                .WithMany(p => p.Order)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Order__user_id__5CD6CB2B");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order> entity);
    }
}
