// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Modelo.Models;
using System;
using System.Collections.Generic;

namespace Modelo.Models.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Brand)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("brand");

            entity.Property(e => e.Description).HasColumnName("description");

            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("model");

            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("price");

            entity.Property(e => e.Ram).HasColumnName("ram");

            entity.Property(e => e.Storage).HasColumnName("storage");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
